# app/core/models.py
from pydantic import BaseModel, Field, EmailStr
from typing import List, Optional, Literal

# --- 1. Router / Intent Definition ---
class RouterOutput(BaseModel):
    flow_action: Optional[Literal["continue", "exit", "detour"]] = Field(
        default=None,
        description=(
            "Only set when an active workflow is in progress. 'continue' if "
            "this message advances the active flow. 'exit' if the user "
            "explicitly cancels/abandons it. 'detour' if the user has shifted "
            "to an unrelated topic without explicitly cancelling. Leave null "
            "if there is no active flow."
        ),
    )
    intent: Literal["conversational_agent", "booking", "lead_capture"] = Field(
        ...,
        description="The ultimate classified goal state or target graph node for execution."
    )

# --- 2. Tool Payload Models ---
class PineconeQueryPayload(BaseModel):
    query: str = Field(description="The semantic query string")
    namespace: str = Field(description="The specific branch namespace to search")
    top_k: int = Field(default=3, description="Number of chunks to retrieve")

class MongoConfigPayload(BaseModel):
    org_id: str
    branch_id: str

# --- 3. API / Graph Return Models ---
class FinalResponse(BaseModel):
    answer: str
    source_documents: List[str]
    metadata: dict = Field(description="Diagnostic info like latency or routing path")

#--- 4. Agent Input Model ---
class AgentInput(BaseModel):
    org_id: str
    branch_id: str
    email: EmailStr
    username: str
    text: str

# --- 5. User Authentication Model ---
class UserAuth(BaseModel):
    org_id: str = Field(..., description="Organization ID")
    branch_id: str = Field(..., description="Branch ID")
    username: str = Field(..., description="User's display name")
    email: EmailStr = Field(..., description="Globally unique email")
    password: str = Field(..., min_length=6)

# --- 6. Chat Message Model ---
class ChatMessage(BaseModel):
    text: str

# --- 7. Lead Capture Models ---
class LeadData(BaseModel):
    product: Optional[str] = None
    reason: Optional[str] = None
    budget: Optional[str] = None
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    phone: Optional[str] = None

class LeadCaptureModel(BaseModel):
    """
    Structured extraction payload generated by the LLM.

    IMPORTANT:
    Populate fields ONLY when the user explicitly provides the value
    in their latest message. Never infer, guess, summarize or derive
    values from previous conversation, recommendations or context.

    The only fields that may already exist without user input are
    authenticated name and email supplied by the application.
    """

    is_relevant_to_lead_capture: bool = Field(
        description=(
            "True if the user is still participating in the lead capture "
            "conversation or answering a lead collection question. "
            "False only when the user clearly changes topics."
        )
    )

    product: Optional[str] = Field(
        default=None,
        description=(
            "The product or service the user explicitly states they are "
            "interested in. Never infer from previous discussion. "
            "If the user says 'the travel package' or "
            "'one of your tours', store the exact text."
        ),
    )

    reason: Optional[str] = Field(
        default=None,
        description=(
            "The user's explicitly stated reason or purpose. "
            "Leave null unless the user directly answers this question."
        ),
    )

    budget: Optional[str] = Field(
        default=None,
        description=(
            "The user's explicitly stated budget. "
            "Do not estimate or infer from context."
        ),
    )

    phone: Optional[str] = Field(
        default=None,
        description=(
            "The user's phone number only if they explicitly provide it."
        ),
    )

    complete: Literal["yes", "no"] = Field(
        description=(
            "Return 'yes' ONLY when every required lead field "
            "(name, email, product, reason, budget and phone) "
            "is already available. Otherwise return 'no'."
        )
    )

    assistant_response: Optional[str] = Field(
        default=None,
        description=(
            "A concise conversational reply. "
            "If information is missing, ask for EXACTLY ONE missing field. "
            "Never ask for multiple fields in one response. "
            "Never mention internal reasoning or extraction."
        ),
    )


# 8. Booking Calendar
class BookingData(BaseModel):
    operation: Optional[str] = None

    service: Optional[str] = None

    requested_date: Optional[str] = None
    requested_time: Optional[str] = None

    appointment_reference: Optional[str] = None

    google_event_id: Optional[str] = None


class BookingCaptureModel(BaseModel):
    """
    Structured extraction payload for the booking workflow.

    Populate fields ONLY when the user explicitly provides them.
    Never infer missing values.
    """

    is_relevant_to_booking: bool = Field(
        description="True if the user is discussing booking, rescheduling or cancelling an appointment."
    )

    operation: Literal[
        "schedule",
        "reschedule",
        "cancel",
    ] = Field(
        description=(
            "The booking operation requested by the user."
        )
    )

    service: Optional[str] = Field(
        default=None,
        description="The service explicitly requested by the user."
    )

    requested_date: Optional[str] = Field(
        default=None,
        description="The exact date expression provided by the user."
    )

    requested_time: Optional[str] = Field(
        default=None,
        description="The exact time expression provided by the user."
    )

    appointment_reference: Optional[str] = Field(
        default=None,
        description=(
            "Any explicit appointment identifier supplied by the user."
            "This may be a date, time, service or event reference."
        )
    )

    assistant_response: Optional[str] = Field(
        default=None,
        description=(
            "Natural conversational reply."
            "If required information is missing, ask for EXACTLY ONE field."
        )
    )

class ServiceResult(BaseModel):
    ok: bool
    error: Optional[str] = None

class BookingAction(BaseModel):
    action: Literal["create", "edit", "delete", "unknown"]


class BookingSlots(BaseModel):
    service: Optional[str] = None
    requested_date: Optional[str] = None         # YYYY-MM-DD
    requested_time: Optional[str] = None         # HH:MM 24h
    appointment_reference: Optional[str] = None  # event_id if user states one